# Site settings

title:  Alan's Kunstkammer# Title of your site
email: alan_wzhang@yahoo.com # Your contant email

description: "Hi, I'm Alan, a UC Berkeley undergrad senior."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alanwz.github.io" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:       # Replace this with your Twitter username
github_username:      alanwz  # Replace this with your GitHub username
linkedin_username:      # Replace this with your LinkedIn username
google_plus_username:   # Replace this with your Google+ username
facebook_username:      # Replace this with your Facebook username
dribbble_username:      # Replace this with your Dribbble username

# Build settings
markdown: kramdown
